import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Angular</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicons/favicon.ico" />
      </Head>

      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main> */}

      {/* <footer className={styles.footer}>
        
      </footer> */}

      <div>
        <div>
          <div class="home-rows">
            {/* <aio-announcement-bar></aio-announcement-bar> */}

            <div
              layout="row"
              layout-xs="column"
              class="home-row homepage-container"
            >
              <div class="promo-img-container promo-1">
                <div>
                  <img
                    height="222"
                    width="340"
                    src="/imge/responsive-framework.svg"
                    alt=""
                    loading="lazy"
                  />
                </div>
              </div>

              <div class="text-container">
                <section
                  aria-labelledby="promo-1-title"
                  class="text-block promo-1-desc l-pad-top-2"
                >
                  <h2 id="promo-1-title" class="text-headline no-anchor">
                    Develop Across All Platforms
                  </h2>
                  <p class="text-body">
                    Learn one way to build applications with Angular and reuse
                    your code and abilities to build apps for any deployment
                    target. For web, mobile web, native mobile and native
                    desktop.
                  </p>
                </section>
              </div>
            </div>
            <hr />

            <div layout="row" layout-xs="column" class="home-row">
              <div class="text-container">
                <section aria-labelledby="promo-2-title" class="text-block">
                  <h2 id="promo-2-title" class="text-headline no-anchor">
                    Speed & Performance
                  </h2>
                  <p class="text-body">
                    Achieve the maximum speed possible on the Web Platform
                    today, and take it further, via Web Workers and server-side
                    rendering.
                  </p>
                  <p class="text-body">
                    Angular puts you in control over scalability. Meet huge data
                    requirements by building data models on RxJS, Immutable.js
                    or another push-model.
                  </p>
                </section>
              </div>

              <div class="promo-img-container promo-2">
                <div>
                  <img
                    height="222"
                    width="323"
                    src="/imge/speed-performance.svg"
                    alt=""
                    loading="lazy"
                  />
                </div>
              </div>
            </div>
            <hr />

            <div layout="row" layout-xs="column" class="home-row">
              <div class="promo-img-container promo-3">
                <div>
                  <img
                    src="/imge/joyful-development.svg"
                    alt=""
                    loading="lazy"
                  />
                </div>
              </div>

              <div class="text-container">
                <section
                  aria-labelledby="promo-3-title"
                  class="text-block promo-3-desc"
                >
                  <h2 id="promo-3-title" class="text-headline no-anchor">
                    Incredible Tooling
                  </h2>
                  <p class="text-body">
                    Build features quickly with simple, declarative templates.
                    Extend the template language with your own components and
                    use a wide array of existing components. Get immediate
                    Angular-specific help and feedback with nearly every IDE and
                    editor. All this comes together so you can focus on building
                    amazing apps rather than trying to make the code work.
                  </p>
                </section>
              </div>
            </div>
            <hr />

            <div layout="row" layout-xs="column" class="home-row">
              <div class="text-container">
                <section
                  aria-labelledby="promo-4-title"
                  class="text-block l-pad-top-2"
                >
                  <h2 id="promo-4-title" class="text-headline no-anchor">
                    Loved by Millions
                  </h2>
                  <p class="text-body">
                    From prototype through global deployment, Angular delivers
                    the productivity and scalable infrastructure that supports
                    Google's largest applications.
                  </p>
                </section>
              </div>

              <div class="promo-img-container promo-4">
                <div>
                  <img
                    src="/imge/loved-by-millions.svg"
                    alt=""
                    width="455"
                    height="228"
                    loading="lazy"
                  />
                </div>
              </div>
            </div>

            <div layout="row" layout-xs="column" class="home-row">
              <a href="start" class="card">
                <img
                  src="/imge/code-icon.svg"
                  alt=""
                  width="70"
                  height="70"
                  loading="lazy"
                />
                <div class="card-text-container">
                  <div class="text-headline">Try it now</div>
                  <p>
                    Explore Angular's capabilities with a ready-made sample app.
                    No setup required.
                  </p>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
